import {StyleSheet, Dimensions} from 'react-native';

const {height, width} = Dimensions.get('window');

const style = StyleSheet.create({
  container: {
    flex: 1,
    width: width,
    height: height,
    backgroundColor: '#FFFFFF',
    
    
  },
  amazonia: {
    width: 168,
    height: 120,
    left: 10,
    top: 291,
    position: 'absolute',
  },
  acre: {
    width: 74,
    height: 38,
    left: 8,
    top: 387,
    position: 'absolute',
  },
  rondonia: {
    width: 61,
    height: 59,
    left: 87,
    top: 390,
    position: 'absolute',
  },
  roraima: {
    width: 56,
    height: 68,
    left: 99,
    top: 259,
    position: 'absolute',
  },
  para: {
    width: 134,
    height: 127,
    left: 150,
    top: 284,
    position: 'absolute',
  },
  matogrosso: {
    width: 116,
    height: 108,
    left: 126,
    top: 383,
    position: 'absolute',
  },
  amapa: {
    width: 52,
    height: 53,
    left: 194,
    top: 269,
    position: 'absolute',
  },
  tocantins: {
    width: 39,
    height: 66,
    left: 225.2,
    top: 351.5,
    position: 'absolute',
  },
  tocantins: {
    width: 52,
    height: 82,
    left: 234,
    top: 359,
    position: 'absolute',
  },
  piaui: {
    width: 59,
    height: 82,
    left: 283,
    top: 337,
    position: 'absolute',
  },
  maranhao: {
    width: 68,
    height: 94,
    left: 260,
    top: 319,
    position: 'absolute',
  },
  goias: {
    width: 56,
    height: 55,
    left: 205,
    top: 411.5,
    position: 'absolute',
  },
  goias: {
    width: 73,
    height: 71,
    left: 210,
    top: 434,
    position: 'absolute',
  },
  matogrossodosul: {
    width: 70,
    height: 69,
    left: 163,
    top: 482,
    position: 'absolute',
  },
  saopaulo: {
    width: 81,
    height: 55,
    left: 215,
    top: 508,
    position: 'absolute',
  },
  minasgerais: {
    width: 112,
    height: 90,
    left: 231,
    top: 452,
    position: 'absolute',
  },
  distrito: {
    width: 39,
    height: 21,
    left: 254,
    top: 456,
    position: 'absolute',
  },
  santacatarina: {
    width: 52,
    height: 35,
    left: 204,
    top: 571,
    position: 'absolute',
  },
  parana: {
    width: 62,
    height: 43,
    left: 197,
    top: 535,
    position: 'absolute',
  },
  riograndedosul: {
    width: 71,
    height: 67,
    left: 172,
    top: 583,
    position: 'absolute',
  },
  rio: {
    width: 42,
    height: 30,
    left: 290,
    top: 522,
    position: 'absolute',
  },
  espiritosanto: {
    width: 34,
    height: 37,
    left: 317,
    top: 491,
    position: 'absolute',
  },
  bahia: {
    width: 82,
    height: 101,
    left: 280,
    top: 397,
    position: 'absolute',
  },
  sergipe: {
    width: 32,
    height: 27,
    left: 360,
    top: 410,
    position: 'absolute',
  },
  alagoas: {
    width: 47,
    height: 26,
    left: 361,
    top: 402,
    position: 'absolute',
  },
  pernambuco: {
    width: 66,
    height: 23,
    left: 331,
    top: 384,
    position: 'absolute',
  },
  paraiba: {
    width: 39,
    height: 25,
    left: 358,
    top: 372,
    position: 'absolute',
  },
  ceara: {
    width: 43,
    height: 54,
    left: 330,
    top: 335,
    position: 'absolute',
  },
  riograndedonorte: {
    width: 37,
    height: 24,
    left: 359,
    top: 359,
    position: 'absolute',
  },
  text: {
    fontSize: 20,
    width: '100%',
    textAlign: 'center',
    color: '#19191B',
    top: 150
  },
});

export default style;
